// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vohmhkmfxofieuoksqra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaG1oa21meG9maWV1b2tzcXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTA5MTEsImV4cCI6MjA2NDAyNjkxMX0.dW8jWxraSj0G5g9kibKoUrF-rl83HH4R5ilnf27pZdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: false, // disable auto retry if project paused
    persistSession: true,
    detectSessionInUrl: false,
  },
  global: {
    fetch: (url, options) => {
      return fetch(url, { 
        ...options, 
        signal: AbortSignal.timeout(5000) // 5 second timeout max
      });
    }
  }
});